import Link from "next/link";
import { Activity, BellRing, Bug, CircleHelp, Coins, FileClock, FileUp, Flag, Gamepad2, Layers3, ShieldAlert, ShoppingBag, Sparkles, UserRoundCheck, UsersRound, type LucideIcon } from "lucide-react";
import { DevelopmentDataNotice } from "@/components/ui/development-data-notice";
import { MetricCard } from "@/components/ui/metric-card";
import { PageHeader } from "@/components/ui/page-header";
import { StatusBadge } from "@/components/ui/status-badge";
import { getDashboardData } from "@/lib/data/admin-data";
import { formatDate, formatNumber } from "@/lib/utils";

export const metadata = { title: "لوحة المؤشرات" };
export const dynamic = "force-dynamic";

export default async function DashboardPage() {
  const data = await getDashboardData(); const maxMatches = Math.max(...data.activity.map((day) => day.matches), 1); const publishRatio = data.totals.questions ? Math.round(data.totals.publishedQuestions / data.totals.questions * 100) : 0;
  return <div className="space-y-6">
    <PageHeader eyebrow="نظرة عامة" title="نبض أحدعش" description="مؤشرات تشغيلية ومحتوى واقتصاد ومراقبة من البيانات الحقيقية، مع وصول مباشر للأشياء التي تحتاج قرارًا." actions={<Link href="/import" className="button-primary"><FileUp size={17} />استيراد أسئلة</Link>} />
    {!data.available ? <DevelopmentDataNotice /> : null}
    {!data.available ? <div className="surface-card p-8 text-center"><Activity className="mx-auto text-[var(--muted)]" /><h2 className="mt-3 font-black">المؤشرات الحقيقية غير متاحة</h2><p className="mt-2 text-sm text-[var(--muted)]">لا نعرض أرقامًا تجريبية. اربط Supabase وطبّق migration الجديدة لتفعيل ملخص الإدارة.</p></div> : <>
      <section className="grid grid-cols-2 gap-3 lg:grid-cols-4 2xl:grid-cols-6">
        <MetricCard label="إجمالي المستخدمين" value={formatNumber(data.totals.users)} change={`${formatNumber(data.totals.newUsers)} جديد خلال 7 أيام`} icon={UsersRound} />
        <MetricCard label="نشط خلال 24 ساعة" value={formatNumber(data.totals.activeUsers)} change="بحسب آخر ظهور موثوق" icon={UserRoundCheck} accent="blue" />
        <MetricCard label="المباريات" value={formatNumber(data.totals.matches)} change={`${formatNumber(data.totals.matchesToday)} اليوم`} icon={Gamepad2} accent="blue" />
        <MetricCard label="الأسئلة" value={formatNumber(data.totals.questions)} change={`${publishRatio}% منشور`} icon={CircleHelp} />
        <MetricCard label="التصنيفات" value={formatNumber(data.totals.categories)} change={`${formatNumber(data.totals.draftQuestions)} سؤال Draft`} icon={Layers3} accent="gold" />
        <MetricCard label="الأخطاء المفتوحة" value={formatNumber(data.totals.errors)} change={`${formatNumber(data.totals.criticalErrors)} حرجة`} icon={Bug} accent="red" />
      </section>
      <section className="grid gap-4 xl:grid-cols-[1.35fr_.9fr]">
        <article className="surface-card p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="eyebrow">الحركة الحقيقية</p><h2 className="mt-2 text-lg font-black">المباريات خلال 7 أيام</h2></div><StatusBadge tone="info">كل الأنماط</StatusBadge></div><div className="mt-7 flex h-52 items-end gap-2 sm:gap-4" aria-label="مخطط المباريات خلال سبعة أيام">{data.activity.map((day, index) => { const height = Math.max(5, Math.round(day.matches / maxMatches * 100)); return <div key={`${day.day}-${index}`} className="flex h-full flex-1 flex-col justify-end gap-2 text-center"><span className="text-[9px] font-bold text-[var(--muted)]">{formatNumber(day.matches)}</span><div className="relative flex-1 overflow-hidden rounded-t-xl bg-black/[0.035]"><span className="absolute inset-x-0 bottom-0 rounded-t-xl bg-gradient-to-t from-[#5f9909] to-[#9bdc35]" style={{ height: `${height}%` }} /></div><span className="text-[10px] font-bold text-[var(--muted)]">{day.day}</span></div>; })}</div></article>
        <article className="surface-card p-5"><p className="eyebrow">أنماط اللعب</p><h2 className="mt-2 text-lg font-black">توزيع المباريات</h2><div className="mt-5 space-y-3"><ModeRow label="ضد النظام" value={data.totals.soloMatches} total={data.totals.matches} /><ModeRow label="1 ضد 1" value={data.totals.oneVOneMatches} total={data.totals.matches} /><ModeRow label="2 ضد 2" value={data.totals.twoVTwoMatches} total={data.totals.matches} /></div></article>
      </section>
      <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <MetricCard label="العملات المتداولة" value={formatNumber(data.totals.coinsCirculation)} change="مجموع أرصدة المحافظ من الخادم" icon={Coins} accent="gold" />
        <MetricCard label="Premium نشط" value={formatNumber(data.totals.premiumUsers)} change="استحقاقات RevenueCat الفعالة" icon={Sparkles} accent="gold" />
        <MetricCard label="عمليات شراء بالعملات" value={formatNumber(data.totals.purchases30d)} change="آخر 30 يومًا، وليست إيرادًا نقديًا" icon={ShoppingBag} accent="blue" />
        <MetricCard label="بلاغات مفتوحة" value={formatNumber(data.totals.questionReports + data.totals.userReports)} change={`${formatNumber(data.totals.userReports)} بلاغ مستخدم`} icon={Flag} accent="red" />
      </section>
      <section className="grid gap-4 xl:grid-cols-3">
        <DashboardList title="آخر مشاكل التطبيق" icon={ShieldAlert} href="/errors" empty="لا توجد مشاكل مسجلة.">{data.latestErrors.map((row) => <li key={row.id} className="flex items-start justify-between gap-3 border-b border-black/7 py-3 last:border-0"><div><p className="text-xs font-black">{row.title}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{formatDate(row.lastSeen)} · {formatNumber(row.count)} تكرار</p></div><StatusBadge tone={row.severity === "critical" || row.severity === "error" ? "danger" : "warning"}>{row.severity}</StatusBadge></li>)}</DashboardList>
        <DashboardList title="آخر محتوى منشور" icon={Sparkles} href="/content" empty="لا يوجد محتوى منشور.">{data.latestContent.map((row) => <li key={row.key} className="flex items-start justify-between gap-3 border-b border-black/7 py-3 last:border-0"><div><p className="text-xs font-black">{row.label}</p><p className="mt-1 font-mono text-[9px] text-[var(--muted)]" dir="ltr">{row.key}</p></div><StatusBadge tone="success">v{row.version}</StatusBadge></li>)}</DashboardList>
        <DashboardList title="آخر نشاطات الإدارة" icon={FileClock} href="/audit" empty="لا يوجد نشاط مسجل.">{data.latestAudit.map((row) => <li key={row.id} className="border-b border-black/7 py-3 last:border-0"><p className="text-xs font-black">{row.action}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{row.entityType} · {formatDate(row.createdAt)}</p></li>)}</DashboardList>
      </section>
      <section className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><article className="surface-card overflow-hidden"><div className="flex items-center justify-between border-b border-black/7 p-5"><div><p className="eyebrow">الاستيراد</p><h2 className="mt-2 font-black">آخر الدفعات</h2></div><Link href="/import" className="text-xs font-bold text-[var(--primary-strong)]">دفعة جديدة</Link></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>الملف</th><th>الصفوف</th><th>التاريخ</th><th>الحالة</th></tr></thead><tbody>{data.latestImports.map((batch) => <tr key={batch.id}><td className="font-bold">{batch.filename}</td><td>{formatNumber(batch.totalRows)}</td><td>{formatDate(batch.createdAt)}</td><td><StatusBadge tone={batch.status === "completed" ? "success" : batch.status === "failed" ? "danger" : "warning"}>{batch.status}</StatusBadge></td></tr>)}{!data.latestImports.length ? <tr><td colSpan={4} className="py-10 text-center">لا توجد دفعات.</td></tr> : null}</tbody></table></div></article><article className="surface-card p-5"><div className="flex items-center gap-2"><BellRing size={18} className="text-[var(--primary-strong)]" /><h2 className="font-black">الإشعارات خلال 7 أيام</h2></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#74b512]/8 p-4"><span className="text-[10px] text-[var(--muted)]">تم إرسالها</span><strong className="mt-2 block text-xl">{formatNumber(data.totals.notificationsSent7d)}</strong></div><div className="rounded-xl bg-[#c83443]/7 p-4"><span className="text-[10px] text-[var(--muted)]">فشلت</span><strong className="mt-2 block text-xl">{formatNumber(data.totals.notificationsFailed7d)}</strong></div></div><Link href="/system-health" className="button-secondary mt-4 w-full">فحص صحة الأنظمة</Link></article></section>
    </>}
  </div>;
}

function ModeRow({ label, value, total }: { label: string; value: number; total: number }) { const ratio = total ? Math.round(value / total * 100) : 0; return <div><div className="mb-2 flex items-center justify-between text-xs"><span className="font-bold">{label}</span><span className="text-[var(--muted)]">{formatNumber(value)} · {ratio}%</span></div><div className="h-2 overflow-hidden rounded-full bg-black/[0.05]"><div className="h-full rounded-full bg-[var(--primary)]" style={{ width: `${ratio}%` }} /></div></div>; }
function DashboardList({ title, icon: Icon, href, empty, children }: { title: string; icon: LucideIcon; href: string; empty: string; children: React.ReactNode }) { const hasChildren = Array.isArray(children) ? children.length > 0 : Boolean(children); return <article className="surface-card p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Icon size={18} className="text-[var(--primary-strong)]" /><h2 className="font-black">{title}</h2></div><Link href={href} className="text-[11px] font-bold text-[var(--primary-strong)]">عرض الكل</Link></div><ul className="mt-3">{hasChildren ? children : <li className="py-8 text-center text-sm text-[var(--muted)]">{empty}</li>}</ul></article>; }
