"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { CircleHelp, FileText, ImageIcon, LoaderCircle, Search, UserRound, X } from "lucide-react";

interface SearchResult { type: "user" | "question" | "category" | "content" | "media"; id: string; title: string; subtitle: string; href: string }
const routes = [
  ["لوحة المؤشرات", "/dashboard"], ["الأسئلة", "/questions"], ["التصنيفات", "/categories"], ["محتوى التطبيق", "/content"], ["مكتبة الوسائط", "/media"], ["هوية التطبيق", "/branding"], ["البطولات", "/tournaments"], ["Football Data", "/football-data"], ["Social", "/social"], ["مشاكل التطبيق", "/errors"], ["بلاغات المستخدمين", "/user-reports"], ["صحة الأنظمة", "/system-health"], ["سجل التدقيق", "/audit"],
] as const;

export function CommandPalette() {
  const router = useRouter(); const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [results, setResults] = useState<SearchResult[]>([]); const [loading, setLoading] = useState(false); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setOpen((value) => !value); } if (event.key === "Escape") setOpen(false); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []);
  useEffect(() => { if (open) setTimeout(() => input.current?.focus(), 0); }, [open]);
  useEffect(() => { if (query.trim().length < 2) return; const controller = new AbortController(); const timer = setTimeout(() => { setLoading(true); void fetch(`/api/search?q=${encodeURIComponent(query.trim())}`, { signal: controller.signal }).then((response) => response.json()).then((body: { results?: SearchResult[] }) => setResults(body.results ?? [])).catch(() => undefined).finally(() => setLoading(false)); }, 250); return () => { clearTimeout(timer); controller.abort(); }; }, [query]);
  const matchingRoutes = useMemo(() => routes.filter(([label]) => !query.trim() || label.includes(query.trim())), [query]);
  function go(href: string) { setOpen(false); setQuery(""); router.push(href); }
  return <><button type="button" onClick={() => setOpen(true)} className="hidden min-h-10 items-center gap-2 rounded-xl border border-black/10 bg-white/80 px-3 text-xs font-bold text-[var(--muted)] sm:flex" aria-label="فتح البحث السريع"><Search size={16} /><span>بحث سريع</span><kbd className="rounded-md bg-black/5 px-1.5 py-0.5 text-[9px]" dir="ltr">Ctrl K</kbd></button>{open ? <div className="fixed inset-0 z-[80] grid items-start justify-center bg-black/35 px-4 pt-[10vh] backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="البحث السريع"><button type="button" className="absolute inset-0" aria-label="إغلاق البحث" onClick={() => setOpen(false)} /><div className="relative w-[min(94vw,42rem)] overflow-hidden rounded-[1.4rem] border border-white/70 bg-[#fffefa]/95 shadow-2xl backdrop-blur-xl"><div className="flex items-center gap-3 border-b border-black/8 px-4"><Search size={19} className="text-[var(--muted)]" /><input ref={input} className="h-16 flex-1 bg-transparent text-base outline-none" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="تنقل أو ابحث في المستخدمين والمحتوى…" /><button type="button" onClick={() => setOpen(false)} className="grid size-9 place-items-center rounded-lg hover:bg-black/5" aria-label="إغلاق"><X size={18} /></button></div><div className="max-h-[60vh] overflow-y-auto p-3"><p className="px-2 py-1 text-[10px] font-black text-[var(--muted)]">التنقل</p>{matchingRoutes.map(([label, href]) => <button key={href} type="button" onClick={() => go(href)} className="flex min-h-11 w-full items-center rounded-xl px-3 text-right text-sm font-bold hover:bg-black/[0.04]">{label}</button>)}{query.trim().length >= 2 ? <><p className="mt-2 flex items-center gap-2 px-2 py-1 text-[10px] font-black text-[var(--muted)]">نتائج البيانات {loading ? <LoaderCircle size={12} className="animate-spin" /> : null}</p>{results.map((result) => <button key={`${result.type}:${result.id}`} type="button" onClick={() => go(result.href)} className="flex min-h-14 w-full items-center gap-3 rounded-xl px-3 text-right hover:bg-black/[0.04]"><ResultIcon type={result.type} /><span className="min-w-0"><strong className="block truncate text-sm">{result.title}</strong><span className="block truncate text-[10px] text-[var(--muted)]">{result.subtitle}</span></span></button>)}{!loading && !results.length ? <p className="p-5 text-center text-sm text-[var(--muted)]">لا توجد نتائج بيانات مطابقة.</p> : null}</> : null}</div></div></div> : null}</>;
}
function ResultIcon({ type }: { type: SearchResult["type"] }) { const Icon = type === "user" ? UserRound : type === "question" ? CircleHelp : type === "media" ? ImageIcon : FileText; return <span className="grid size-9 shrink-0 place-items-center rounded-lg bg-[#74b512]/8 text-[#5f9909]"><Icon size={16} /></span>; }
