import 'store_item.dart';

abstract final class LaunchStoreCatalog {
  static final List<StoreItem> items = List.unmodifiable([
    _item(
      1,
      'card_tunnel_lime',
      'نفق الحسم',
      'نفق Lime يفتح بطاقتك على أجواء المباراة.',
      StoreCategory.profileBackground,
      420,
      StoreRarity.rare,
      featured: true,
    ),
    _item(
      2,
      'card_night_pitch',
      'ملعب الليل',
      'ملعب هادئ تحت الكشافات لبطاقة أكثر هيبة.',
      StoreCategory.profileBackground,
      520,
      StoreRarity.rare,
      isNew: true,
    ),
    _item(
      3,
      'card_gold_stage',
      'منصة الذهب',
      'إضاءة ذهبية مركزة للحظات المستوى العالي.',
      StoreCategory.profileBackground,
      760,
      StoreRarity.epic,
      featured: true,
    ),
    _item(
      4,
      'card_sand_geometry',
      'هندسة الفريق',
      'تكوين دافئ بخطوط اجتماعية وكروية أصلية.',
      StoreCategory.profileBackground,
      610,
      StoreRarity.epic,
    ),
    _item(
      5,
      'frame_tactical',
      'إطار التكتيك',
      'حواف فحمية مع مسار Lime حاد وواضح.',
      StoreCategory.profileFrame,
      350,
      StoreRarity.common,
    ),
    _item(
      6,
      'frame_gold_step',
      'إطار المدرج الذهبي',
      'إطار متدرج بلمعة ذهبية هادئة.',
      StoreCategory.profileFrame,
      690,
      StoreRarity.epic,
      featured: true,
    ),
    _item(
      7,
      'frame_sand_cut',
      'إطار الرمل',
      'قصّات هندسية بلون رملي حديث.',
      StoreCategory.profileFrame,
      460,
      StoreRarity.rare,
      isNew: true,
    ),
    _item(
      8,
      'style_pitch_diagonal',
      'ستايل خط الملعب',
      'ألواح قطرية مستوحاة من خطوط الملعب.',
      StoreCategory.player11Style,
      390,
      StoreRarity.rare,
    ),
    _item(
      9,
      'style_nocturne_split',
      'ستايل ليلة المباراة',
      'تقسيم ليلي متوازن بلمسة ذهبية.',
      StoreCategory.player11Style,
      480,
      StoreRarity.rare,
      isNew: true,
    ),
    _item(
      10,
      'style_desert_blocks',
      'ستايل مدرج الصحراء',
      'طبقات رملية متدرجة بتكوين مختلف.',
      StoreCategory.player11Style,
      630,
      StoreRarity.epic,
    ),
    _item(
      11,
      'style_stadium_wave',
      'ستايل موجة الجمهور',
      'موجات Lime متحركة بصريًا حول Player 11.',
      StoreCategory.player11Style,
      820,
      StoreRarity.legendary,
      featured: true,
    ),
    _item(
      12,
      'team_tactics',
      'راية الخطة',
      'نمط تمريرات وخطوط ملعب للفريق.',
      StoreCategory.teamPattern,
      440,
      StoreRarity.rare,
    ),
    _item(
      13,
      'team_sadu_step',
      'راية الدرج الرملي',
      'هندسة متدرجة مستوحاة برفق من النسيج المحلي.',
      StoreCategory.teamPattern,
      580,
      StoreRarity.epic,
      isNew: true,
    ),
    _item(
      14,
      'team_stadium_wave',
      'راية الموجة',
      'موجة كشافات سريعة بهوية فريق واضحة.',
      StoreCategory.teamPattern,
      720,
      StoreRarity.epic,
    ),
    _item(
      15,
      'victory_lime_spiral',
      'احتفال الدوامة',
      'دوامة Lime ترتفع عند إعلان الفوز.',
      StoreCategory.victoryEffect,
      850,
      StoreRarity.legendary,
      featured: true,
    ),
    _item(
      16,
      'victory_gold_prism',
      'احتفال المنشور',
      'شظايا ضوء ذهبية هندسية بلا ضوضاء.',
      StoreCategory.victoryEffect,
      920,
      StoreRarity.legendary,
      isNew: true,
    ),
    _item(
      17,
      'nameplate_tactical',
      'لوحة صانع اللعب',
      'لوحة فحمية طويلة بحافة تكتيكية.',
      StoreCategory.nameplate,
      280,
      StoreRarity.common,
    ),
    _item(
      18,
      'nameplate_majlis_gold',
      'لوحة القائد',
      'لوحة رملية ذهبية لاسمك داخل الفريق.',
      StoreCategory.nameplate,
      540,
      StoreRarity.epic,
    ),
    _item(
      19,
      'answer_effect_pitch_pulse',
      'نبضة الملعب',
      'دوائر ملعب تظهر بعد نتيجة الإجابة.',
      StoreCategory.answerEffect,
      470,
      StoreRarity.rare,
      isNew: true,
    ),
    _item(
      20,
      'lobby_tactical_room',
      'غرفة الخطة',
      'خلفية تكتيكية هادئة لغرفة الانتظار.',
      StoreCategory.lobbyBackground,
      660,
      StoreRarity.epic,
    ),
  ]);

  static StoreItem _item(
    int sequence,
    String sku,
    String name,
    String description,
    StoreCategory category,
    int price,
    StoreRarity rarity, {
    bool featured = false,
    bool isNew = false,
  }) => StoreItem(
    id: '11000000-0000-4000-8000-${sequence.toString().padLeft(12, '0')}',
    sku: sku,
    name: name,
    description: description,
    type: StoreItemType.cosmetic,
    category: category,
    priceCoins: price,
    imageAsset: StoreItem.localAssetForSku(sku),
    previewAsset: StoreItem.localAssetForSku(sku),
    rarity: rarity,
    assetRights: 'original-generated-safe',
    sortOrder: sequence * 10,
    isFeatured: featured,
    isNew: isNew,
  );
}
